# Generated by Django 4.0.4 on 2022-05-13 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_rename_first_autor_apelido_rename_last_autor_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=5000)),
                ('imagem', models.ImageField(upload_to='')),
                ('ano', models.DateField()),
                ('linkGithub', models.CharField(max_length=1000)),
                ('linkYoutube', models.CharField(max_length=1000)),
                ('tecnologias', models.CharField(max_length=1000)),
                ('competencias', models.CharField(max_length=1000)),
                ('participantes', models.ManyToManyField(to='portfolio.autor')),
            ],
        ),
        migrations.CreateModel(
            name='Cadeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('ects', models.IntegerField()),
                ('data', models.DateField()),
                ('topicosAbordados', models.CharField(max_length=1000)),
                ('ranking', models.IntegerField()),
                ('link', models.CharField(max_length=1000)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor', to='portfolio.autor')),
                ('projetos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='portfolio.projeto')),
            ],
        ),
    ]
