# Generated by Django 4.0.4 on 2022-05-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_projeto_cadeira'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interesse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(upload_to='')),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('acronimo', models.CharField(max_length=20)),
                ('ano', models.DateField()),
                ('criador', models.CharField(max_length=20)),
                ('logo', models.ImageField(upload_to='')),
                ('link', models.URLField()),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Autor',
            new_name='Pessoa',
        ),
        migrations.DeleteModel(
            name='Cadeira',
        ),
    ]
