# Generated by Django 4.0.4 on 2022-05-16 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_interesse_tecnologia_rename_autor_pessoa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('ano', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('descricao', models.TextField(max_length=2000)),
                ('ects', models.IntegerField()),
                ('data', models.DateField()),
                ('topicosAbordados', models.CharField(max_length=1000)),
                ('ranking', models.IntegerField()),
                ('link', models.URLField()),
                ('docente_teorica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.pessoa')),
                ('docentes_praticas', models.ManyToManyField(related_name='caderias', to='portfolio.pessoa')),
                ('linguagens', models.ManyToManyField(to='portfolio.tecnologia')),
                ('projetos', models.ManyToManyField(to='portfolio.projeto')),
            ],
        ),
    ]
