# Generated by Django 4.0.4 on 2022-05-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_cadeira'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='projeto',
            name='imagem',
            field=models.ImageField(upload_to='projetos'),
        ),
        migrations.AlterField(
            model_name='tecnologia',
            name='nome',
            field=models.CharField(max_length=30),
        ),
    ]
