# Generated by Django 4.0.4 on 2022-05-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_laboratorio_alter_projeto_imagem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=50)),
                ('local', models.CharField(max_length=50)),
                ('inicio', models.CharField(max_length=50)),
                ('fim', models.CharField(max_length=50)),
                ('imagem', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='cadeira',
            name='data',
        ),
        migrations.RemoveField(
            model_name='cadeira',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='tecnologias',
        ),
        migrations.AddField(
            model_name='projeto',
            name='tecnologias',
            field=models.ManyToManyField(to='portfolio.tecnologia'),
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=1000)),
                ('disciplinas', models.ManyToManyField(to='portfolio.cadeira')),
                ('tecnologias', models.ManyToManyField(to='portfolio.projeto')),
            ],
        ),
    ]
