# Generated by Django 4.0.4 on 2022-05-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_formacao_remove_cadeira_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadeira',
            name='anoLetivo',
            field=models.IntegerField(default=1),
        ),
    ]
