# Generated by Django 4.0.4 on 2022-05-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_cadeira_ano_alter_cadeira_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadeira',
            name='ranking',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=2),
        ),
    ]
