# Generated by Django 4.0.4 on 2022-05-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_alter_cadeira_ranking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadeira',
            name='anoLetivo',
        ),
        migrations.AddField(
            model_name='cadeira',
            name='anoLectivo',
            field=models.CharField(choices=[(1, 'ano1'), (2, 'ano2'), (3, 'ano3')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='ano',
            field=models.IntegerField(default=2021),
        ),
    ]
