# Generated by Django 4.0.4 on 2022-05-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_alter_cadeira_projetos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='linkLinkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='linkLusofona',
            field=models.URLField(blank=True),
        ),
    ]
