# Generated by Django 4.0.4 on 2022-05-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_pessoa_linklinkedin_pessoa_linklusofona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadeira',
            name='linguagens',
            field=models.ManyToManyField(blank=True, to='portfolio.tecnologia'),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='topicosAbordados',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
