# Generated by Django 4.0.4 on 2022-05-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_alter_cadeira_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadeira',
            name='anoLectivo',
            field=models.CharField(choices=[('ano1', '1'), ('ano2', '2'), ('ano3', '3')], default='1', max_length=4),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='ranking',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=2),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='semestre',
            field=models.CharField(choices=[('sem1', '1'), ('sem2', '2')], max_length=4),
        ),
    ]
