# Generated by Django 4.0.4 on 2022-05-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_alter_cadeira_anolectivo_alter_cadeira_ranking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='funcao',
            field=models.CharField(blank=True, choices=[('aluno', 'aluno'), ('professor', 'professor')], max_length=20),
        ),
    ]
