# Generated by Django 4.0.4 on 2022-05-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_pessoa_funcao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadeira',
            name='topicosAbordados',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
