# Generated by Django 4.0.4 on 2022-05-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_alter_cadeira_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competencia',
            old_name='tecnologias',
            new_name='projetos',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='competencias',
        ),
        migrations.AlterField(
            model_name='projeto',
            name='linkGithub',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='linkYoutube',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
