# Generated by Django 4.0.4 on 2022-05-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_rename_tecnologias_competencia_projetos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(max_length=5000),
        ),
    ]
